language: php
php:
  - '5.5'
  - '5.6'
before_install:
  - phpenv config-rm xdebug.ini
install: composer install --prefer-dist
script:
  - php vendor/bin/phpunit --bootstrap vendor/autoload.php test
  - vendor/bin/phpcs src
  - vendor/bin/phpmd src text cleancode
