language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
install: composer install
script:
  - php vendor/bin/phpunit --bootstrap vendor/autoload.php test
  - vendor/bin/phpcs src
  - vendor/bin/phpmd src text cleancode